# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/sistek/software/cmake-3.6.0-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/sistek/software/cmake-3.6.0-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sistek/programming/p4est-bddcml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sistek/programming/p4est-bddcml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/sistek/software/cmake-3.6.0-Linux-x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/sistek/software/cmake-3.6.0-Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sistek/programming/p4est-bddcml/CMakeFiles /home/sistek/programming/p4est-bddcml/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sistek/programming/p4est-bddcml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uniform_conv

# Build rule for target.
uniform_conv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uniform_conv
.PHONY : uniform_conv

# fast build rule for target.
uniform_conv/fast:
	$(MAKE) -f CMakeFiles/uniform_conv.dir/build.make CMakeFiles/uniform_conv.dir/build
.PHONY : uniform_conv/fast

#=============================================================================
# Target rules for targets named p4est_bddcml

# Build rule for target.
p4est_bddcml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p4est_bddcml
.PHONY : p4est_bddcml

# fast build rule for target.
p4est_bddcml/fast:
	$(MAKE) -f CMakeFiles/p4est_bddcml.dir/build.make CMakeFiles/p4est_bddcml.dir/build
.PHONY : p4est_bddcml/fast

#=============================================================================
# Target rules for targets named test_quadrature

# Build rule for target.
test_quadrature: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_quadrature
.PHONY : test_quadrature

# fast build rule for target.
test_quadrature/fast:
	$(MAKE) -f CMakeFiles/test_quadrature.dir/build.make CMakeFiles/test_quadrature.dir/build
.PHONY : test_quadrature/fast

#=============================================================================
# Target rules for targets named mylib

# Build rule for target.
mylib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mylib
.PHONY : mylib

# fast build rule for target.
mylib/fast:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/build
.PHONY : mylib/fast

drivers/p4est_bddcml.o: drivers/p4est_bddcml.cc.o

.PHONY : drivers/p4est_bddcml.o

# target to build an object file
drivers/p4est_bddcml.cc.o:
	$(MAKE) -f CMakeFiles/p4est_bddcml.dir/build.make CMakeFiles/p4est_bddcml.dir/drivers/p4est_bddcml.cc.o
.PHONY : drivers/p4est_bddcml.cc.o

drivers/p4est_bddcml.i: drivers/p4est_bddcml.cc.i

.PHONY : drivers/p4est_bddcml.i

# target to preprocess a source file
drivers/p4est_bddcml.cc.i:
	$(MAKE) -f CMakeFiles/p4est_bddcml.dir/build.make CMakeFiles/p4est_bddcml.dir/drivers/p4est_bddcml.cc.i
.PHONY : drivers/p4est_bddcml.cc.i

drivers/p4est_bddcml.s: drivers/p4est_bddcml.cc.s

.PHONY : drivers/p4est_bddcml.s

# target to generate assembly for a file
drivers/p4est_bddcml.cc.s:
	$(MAKE) -f CMakeFiles/p4est_bddcml.dir/build.make CMakeFiles/p4est_bddcml.dir/drivers/p4est_bddcml.cc.s
.PHONY : drivers/p4est_bddcml.cc.s

drivers/test_quadrature.o: drivers/test_quadrature.cc.o

.PHONY : drivers/test_quadrature.o

# target to build an object file
drivers/test_quadrature.cc.o:
	$(MAKE) -f CMakeFiles/test_quadrature.dir/build.make CMakeFiles/test_quadrature.dir/drivers/test_quadrature.cc.o
.PHONY : drivers/test_quadrature.cc.o

drivers/test_quadrature.i: drivers/test_quadrature.cc.i

.PHONY : drivers/test_quadrature.i

# target to preprocess a source file
drivers/test_quadrature.cc.i:
	$(MAKE) -f CMakeFiles/test_quadrature.dir/build.make CMakeFiles/test_quadrature.dir/drivers/test_quadrature.cc.i
.PHONY : drivers/test_quadrature.cc.i

drivers/test_quadrature.s: drivers/test_quadrature.cc.s

.PHONY : drivers/test_quadrature.s

# target to generate assembly for a file
drivers/test_quadrature.cc.s:
	$(MAKE) -f CMakeFiles/test_quadrature.dir/build.make CMakeFiles/test_quadrature.dir/drivers/test_quadrature.cc.s
.PHONY : drivers/test_quadrature.cc.s

drivers/uniform_conv.o: drivers/uniform_conv.cc.o

.PHONY : drivers/uniform_conv.o

# target to build an object file
drivers/uniform_conv.cc.o:
	$(MAKE) -f CMakeFiles/uniform_conv.dir/build.make CMakeFiles/uniform_conv.dir/drivers/uniform_conv.cc.o
.PHONY : drivers/uniform_conv.cc.o

drivers/uniform_conv.i: drivers/uniform_conv.cc.i

.PHONY : drivers/uniform_conv.i

# target to preprocess a source file
drivers/uniform_conv.cc.i:
	$(MAKE) -f CMakeFiles/uniform_conv.dir/build.make CMakeFiles/uniform_conv.dir/drivers/uniform_conv.cc.i
.PHONY : drivers/uniform_conv.cc.i

drivers/uniform_conv.s: drivers/uniform_conv.cc.s

.PHONY : drivers/uniform_conv.s

# target to generate assembly for a file
drivers/uniform_conv.cc.s:
	$(MAKE) -f CMakeFiles/uniform_conv.dir/build.make CMakeFiles/uniform_conv.dir/drivers/uniform_conv.cc.s
.PHONY : drivers/uniform_conv.cc.s

src/analytical_solution.o: src/analytical_solution.cc.o

.PHONY : src/analytical_solution.o

# target to build an object file
src/analytical_solution.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/analytical_solution.cc.o
.PHONY : src/analytical_solution.cc.o

src/analytical_solution.i: src/analytical_solution.cc.i

.PHONY : src/analytical_solution.i

# target to preprocess a source file
src/analytical_solution.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/analytical_solution.cc.i
.PHONY : src/analytical_solution.cc.i

src/analytical_solution.s: src/analytical_solution.cc.s

.PHONY : src/analytical_solution.s

# target to generate assembly for a file
src/analytical_solution.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/analytical_solution.cc.s
.PHONY : src/analytical_solution.cc.s

src/assemble.o: src/assemble.cc.o

.PHONY : src/assemble.o

# target to build an object file
src/assemble.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/assemble.cc.o
.PHONY : src/assemble.cc.o

src/assemble.i: src/assemble.cc.i

.PHONY : src/assemble.i

# target to preprocess a source file
src/assemble.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/assemble.cc.i
.PHONY : src/assemble.cc.i

src/assemble.s: src/assemble.cc.s

.PHONY : src/assemble.s

# target to generate assembly for a file
src/assemble.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/assemble.cc.s
.PHONY : src/assemble.cc.s

src/bddcml/arrays.o: src/bddcml/arrays.cc.o

.PHONY : src/bddcml/arrays.o

# target to build an object file
src/bddcml/arrays.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/arrays.cc.o
.PHONY : src/bddcml/arrays.cc.o

src/bddcml/arrays.i: src/bddcml/arrays.cc.i

.PHONY : src/bddcml/arrays.i

# target to preprocess a source file
src/bddcml/arrays.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/arrays.cc.i
.PHONY : src/bddcml/arrays.cc.i

src/bddcml/arrays.s: src/bddcml/arrays.cc.s

.PHONY : src/bddcml/arrays.s

# target to generate assembly for a file
src/bddcml/arrays.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/arrays.cc.s
.PHONY : src/bddcml/arrays.cc.s

src/bddcml/bddcml_femspace.o: src/bddcml/bddcml_femspace.cc.o

.PHONY : src/bddcml/bddcml_femspace.o

# target to build an object file
src/bddcml/bddcml_femspace.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_femspace.cc.o
.PHONY : src/bddcml/bddcml_femspace.cc.o

src/bddcml/bddcml_femspace.i: src/bddcml/bddcml_femspace.cc.i

.PHONY : src/bddcml/bddcml_femspace.i

# target to preprocess a source file
src/bddcml/bddcml_femspace.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_femspace.cc.i
.PHONY : src/bddcml/bddcml_femspace.cc.i

src/bddcml/bddcml_femspace.s: src/bddcml/bddcml_femspace.cc.s

.PHONY : src/bddcml/bddcml_femspace.s

# target to generate assembly for a file
src/bddcml/bddcml_femspace.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_femspace.cc.s
.PHONY : src/bddcml/bddcml_femspace.cc.s

src/bddcml/bddcml_mesh.o: src/bddcml/bddcml_mesh.cc.o

.PHONY : src/bddcml/bddcml_mesh.o

# target to build an object file
src/bddcml/bddcml_mesh.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_mesh.cc.o
.PHONY : src/bddcml/bddcml_mesh.cc.o

src/bddcml/bddcml_mesh.i: src/bddcml/bddcml_mesh.cc.i

.PHONY : src/bddcml/bddcml_mesh.i

# target to preprocess a source file
src/bddcml/bddcml_mesh.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_mesh.cc.i
.PHONY : src/bddcml/bddcml_mesh.cc.i

src/bddcml/bddcml_mesh.s: src/bddcml/bddcml_mesh.cc.s

.PHONY : src/bddcml/bddcml_mesh.s

# target to generate assembly for a file
src/bddcml/bddcml_mesh.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_mesh.cc.s
.PHONY : src/bddcml/bddcml_mesh.cc.s

src/bddcml/bddcml_solver.o: src/bddcml/bddcml_solver.cc.o

.PHONY : src/bddcml/bddcml_solver.o

# target to build an object file
src/bddcml/bddcml_solver.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_solver.cc.o
.PHONY : src/bddcml/bddcml_solver.cc.o

src/bddcml/bddcml_solver.i: src/bddcml/bddcml_solver.cc.i

.PHONY : src/bddcml/bddcml_solver.i

# target to preprocess a source file
src/bddcml/bddcml_solver.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_solver.cc.i
.PHONY : src/bddcml/bddcml_solver.cc.i

src/bddcml/bddcml_solver.s: src/bddcml/bddcml_solver.cc.s

.PHONY : src/bddcml/bddcml_solver.s

# target to generate assembly for a file
src/bddcml/bddcml_solver.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_solver.cc.s
.PHONY : src/bddcml/bddcml_solver.cc.s

src/bddcml/bddcml_structs.o: src/bddcml/bddcml_structs.cc.o

.PHONY : src/bddcml/bddcml_structs.o

# target to build an object file
src/bddcml/bddcml_structs.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_structs.cc.o
.PHONY : src/bddcml/bddcml_structs.cc.o

src/bddcml/bddcml_structs.i: src/bddcml/bddcml_structs.cc.i

.PHONY : src/bddcml/bddcml_structs.i

# target to preprocess a source file
src/bddcml/bddcml_structs.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_structs.cc.i
.PHONY : src/bddcml/bddcml_structs.cc.i

src/bddcml/bddcml_structs.s: src/bddcml/bddcml_structs.cc.s

.PHONY : src/bddcml/bddcml_structs.s

# target to generate assembly for a file
src/bddcml/bddcml_structs.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/bddcml/bddcml_structs.cc.s
.PHONY : src/bddcml/bddcml_structs.cc.s

src/definitions.o: src/definitions.cc.o

.PHONY : src/definitions.o

# target to build an object file
src/definitions.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/definitions.cc.o
.PHONY : src/definitions.cc.o

src/definitions.i: src/definitions.cc.i

.PHONY : src/definitions.i

# target to preprocess a source file
src/definitions.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/definitions.cc.i
.PHONY : src/definitions.cc.i

src/definitions.s: src/definitions.cc.s

.PHONY : src/definitions.s

# target to generate assembly for a file
src/definitions.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/definitions.cc.s
.PHONY : src/definitions.cc.s

src/element.o: src/element.cc.o

.PHONY : src/element.o

# target to build an object file
src/element.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/element.cc.o
.PHONY : src/element.cc.o

src/element.i: src/element.cc.i

.PHONY : src/element.i

# target to preprocess a source file
src/element.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/element.cc.i
.PHONY : src/element.cc.i

src/element.s: src/element.cc.s

.PHONY : src/element.s

# target to generate assembly for a file
src/element.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/element.cc.s
.PHONY : src/element.cc.s

src/gauss_quadrature.o: src/gauss_quadrature.cc.o

.PHONY : src/gauss_quadrature.o

# target to build an object file
src/gauss_quadrature.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/gauss_quadrature.cc.o
.PHONY : src/gauss_quadrature.cc.o

src/gauss_quadrature.i: src/gauss_quadrature.cc.i

.PHONY : src/gauss_quadrature.i

# target to preprocess a source file
src/gauss_quadrature.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/gauss_quadrature.cc.i
.PHONY : src/gauss_quadrature.cc.i

src/gauss_quadrature.s: src/gauss_quadrature.cc.s

.PHONY : src/gauss_quadrature.s

# target to generate assembly for a file
src/gauss_quadrature.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/gauss_quadrature.cc.s
.PHONY : src/gauss_quadrature.cc.s

src/geometry_mesh.o: src/geometry_mesh.cc.o

.PHONY : src/geometry_mesh.o

# target to build an object file
src/geometry_mesh.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/geometry_mesh.cc.o
.PHONY : src/geometry_mesh.cc.o

src/geometry_mesh.i: src/geometry_mesh.cc.i

.PHONY : src/geometry_mesh.i

# target to preprocess a source file
src/geometry_mesh.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/geometry_mesh.cc.i
.PHONY : src/geometry_mesh.cc.i

src/geometry_mesh.s: src/geometry_mesh.cc.s

.PHONY : src/geometry_mesh.s

# target to generate assembly for a file
src/geometry_mesh.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/geometry_mesh.cc.s
.PHONY : src/geometry_mesh.cc.s

src/integral.o: src/integral.cc.o

.PHONY : src/integral.o

# target to build an object file
src/integral.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/integral.cc.o
.PHONY : src/integral.cc.o

src/integral.i: src/integral.cc.i

.PHONY : src/integral.i

# target to preprocess a source file
src/integral.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/integral.cc.i
.PHONY : src/integral.cc.i

src/integral.s: src/integral.cc.s

.PHONY : src/integral.s

# target to generate assembly for a file
src/integral.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/integral.cc.s
.PHONY : src/integral.cc.s

src/integration_cell.o: src/integration_cell.cc.o

.PHONY : src/integration_cell.o

# target to build an object file
src/integration_cell.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/integration_cell.cc.o
.PHONY : src/integration_cell.cc.o

src/integration_cell.i: src/integration_cell.cc.i

.PHONY : src/integration_cell.i

# target to preprocess a source file
src/integration_cell.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/integration_cell.cc.i
.PHONY : src/integration_cell.cc.i

src/integration_cell.s: src/integration_cell.cc.s

.PHONY : src/integration_cell.s

# target to generate assembly for a file
src/integration_cell.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/integration_cell.cc.s
.PHONY : src/integration_cell.cc.s

src/level_set.o: src/level_set.cc.o

.PHONY : src/level_set.o

# target to build an object file
src/level_set.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/level_set.cc.o
.PHONY : src/level_set.cc.o

src/level_set.i: src/level_set.cc.i

.PHONY : src/level_set.i

# target to preprocess a source file
src/level_set.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/level_set.cc.i
.PHONY : src/level_set.cc.i

src/level_set.s: src/level_set.cc.s

.PHONY : src/level_set.s

# target to generate assembly for a file
src/level_set.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/level_set.cc.s
.PHONY : src/level_set.cc.s

src/local_matrix.o: src/local_matrix.cc.o

.PHONY : src/local_matrix.o

# target to build an object file
src/local_matrix.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/local_matrix.cc.o
.PHONY : src/local_matrix.cc.o

src/local_matrix.i: src/local_matrix.cc.i

.PHONY : src/local_matrix.i

# target to preprocess a source file
src/local_matrix.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/local_matrix.cc.i
.PHONY : src/local_matrix.cc.i

src/local_matrix.s: src/local_matrix.cc.s

.PHONY : src/local_matrix.s

# target to generate assembly for a file
src/local_matrix.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/local_matrix.cc.s
.PHONY : src/local_matrix.cc.s

src/local_solution.o: src/local_solution.cc.o

.PHONY : src/local_solution.o

# target to build an object file
src/local_solution.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/local_solution.cc.o
.PHONY : src/local_solution.cc.o

src/local_solution.i: src/local_solution.cc.i

.PHONY : src/local_solution.i

# target to preprocess a source file
src/local_solution.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/local_solution.cc.i
.PHONY : src/local_solution.cc.i

src/local_solution.s: src/local_solution.cc.s

.PHONY : src/local_solution.s

# target to generate assembly for a file
src/local_solution.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/local_solution.cc.s
.PHONY : src/local_solution.cc.s

src/p4est/my_p4est_implementation.o: src/p4est/my_p4est_implementation.cc.o

.PHONY : src/p4est/my_p4est_implementation.o

# target to build an object file
src/p4est/my_p4est_implementation.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/p4est/my_p4est_implementation.cc.o
.PHONY : src/p4est/my_p4est_implementation.cc.o

src/p4est/my_p4est_implementation.i: src/p4est/my_p4est_implementation.cc.i

.PHONY : src/p4est/my_p4est_implementation.i

# target to preprocess a source file
src/p4est/my_p4est_implementation.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/p4est/my_p4est_implementation.cc.i
.PHONY : src/p4est/my_p4est_implementation.cc.i

src/p4est/my_p4est_implementation.s: src/p4est/my_p4est_implementation.cc.s

.PHONY : src/p4est/my_p4est_implementation.s

# target to generate assembly for a file
src/p4est/my_p4est_implementation.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/p4est/my_p4est_implementation.cc.s
.PHONY : src/p4est/my_p4est_implementation.cc.s

src/p4est/my_p4est_interface.o: src/p4est/my_p4est_interface.cc.o

.PHONY : src/p4est/my_p4est_interface.o

# target to build an object file
src/p4est/my_p4est_interface.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/p4est/my_p4est_interface.cc.o
.PHONY : src/p4est/my_p4est_interface.cc.o

src/p4est/my_p4est_interface.i: src/p4est/my_p4est_interface.cc.i

.PHONY : src/p4est/my_p4est_interface.i

# target to preprocess a source file
src/p4est/my_p4est_interface.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/p4est/my_p4est_interface.cc.i
.PHONY : src/p4est/my_p4est_interface.cc.i

src/p4est/my_p4est_interface.s: src/p4est/my_p4est_interface.cc.s

.PHONY : src/p4est/my_p4est_interface.s

# target to generate assembly for a file
src/p4est/my_p4est_interface.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/p4est/my_p4est_interface.cc.s
.PHONY : src/p4est/my_p4est_interface.cc.s

src/p4est/my_p8est_implementation.o: src/p4est/my_p8est_implementation.cc.o

.PHONY : src/p4est/my_p8est_implementation.o

# target to build an object file
src/p4est/my_p8est_implementation.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/p4est/my_p8est_implementation.cc.o
.PHONY : src/p4est/my_p8est_implementation.cc.o

src/p4est/my_p8est_implementation.i: src/p4est/my_p8est_implementation.cc.i

.PHONY : src/p4est/my_p8est_implementation.i

# target to preprocess a source file
src/p4est/my_p8est_implementation.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/p4est/my_p8est_implementation.cc.i
.PHONY : src/p4est/my_p8est_implementation.cc.i

src/p4est/my_p8est_implementation.s: src/p4est/my_p8est_implementation.cc.s

.PHONY : src/p4est/my_p8est_implementation.s

# target to generate assembly for a file
src/p4est/my_p8est_implementation.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/p4est/my_p8est_implementation.cc.s
.PHONY : src/p4est/my_p8est_implementation.cc.s

src/quadrature.o: src/quadrature.cc.o

.PHONY : src/quadrature.o

# target to build an object file
src/quadrature.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/quadrature.cc.o
.PHONY : src/quadrature.cc.o

src/quadrature.i: src/quadrature.cc.i

.PHONY : src/quadrature.i

# target to preprocess a source file
src/quadrature.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/quadrature.cc.i
.PHONY : src/quadrature.cc.i

src/quadrature.s: src/quadrature.cc.s

.PHONY : src/quadrature.s

# target to generate assembly for a file
src/quadrature.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/quadrature.cc.s
.PHONY : src/quadrature.cc.s

src/shapefun.o: src/shapefun.cc.o

.PHONY : src/shapefun.o

# target to build an object file
src/shapefun.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/shapefun.cc.o
.PHONY : src/shapefun.cc.o

src/shapefun.i: src/shapefun.cc.i

.PHONY : src/shapefun.i

# target to preprocess a source file
src/shapefun.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/shapefun.cc.i
.PHONY : src/shapefun.cc.i

src/shapefun.s: src/shapefun.cc.s

.PHONY : src/shapefun.s

# target to generate assembly for a file
src/shapefun.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/shapefun.cc.s
.PHONY : src/shapefun.cc.s

src/vtk_output.o: src/vtk_output.cc.o

.PHONY : src/vtk_output.o

# target to build an object file
src/vtk_output.cc.o:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/vtk_output.cc.o
.PHONY : src/vtk_output.cc.o

src/vtk_output.i: src/vtk_output.cc.i

.PHONY : src/vtk_output.i

# target to preprocess a source file
src/vtk_output.cc.i:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/vtk_output.cc.i
.PHONY : src/vtk_output.cc.i

src/vtk_output.s: src/vtk_output.cc.s

.PHONY : src/vtk_output.s

# target to generate assembly for a file
src/vtk_output.cc.s:
	$(MAKE) -f CMakeFiles/mylib.dir/build.make CMakeFiles/mylib.dir/src/vtk_output.cc.s
.PHONY : src/vtk_output.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... uniform_conv"
	@echo "... p4est_bddcml"
	@echo "... test_quadrature"
	@echo "... mylib"
	@echo "... drivers/p4est_bddcml.o"
	@echo "... drivers/p4est_bddcml.i"
	@echo "... drivers/p4est_bddcml.s"
	@echo "... drivers/test_quadrature.o"
	@echo "... drivers/test_quadrature.i"
	@echo "... drivers/test_quadrature.s"
	@echo "... drivers/uniform_conv.o"
	@echo "... drivers/uniform_conv.i"
	@echo "... drivers/uniform_conv.s"
	@echo "... src/analytical_solution.o"
	@echo "... src/analytical_solution.i"
	@echo "... src/analytical_solution.s"
	@echo "... src/assemble.o"
	@echo "... src/assemble.i"
	@echo "... src/assemble.s"
	@echo "... src/bddcml/arrays.o"
	@echo "... src/bddcml/arrays.i"
	@echo "... src/bddcml/arrays.s"
	@echo "... src/bddcml/bddcml_femspace.o"
	@echo "... src/bddcml/bddcml_femspace.i"
	@echo "... src/bddcml/bddcml_femspace.s"
	@echo "... src/bddcml/bddcml_mesh.o"
	@echo "... src/bddcml/bddcml_mesh.i"
	@echo "... src/bddcml/bddcml_mesh.s"
	@echo "... src/bddcml/bddcml_solver.o"
	@echo "... src/bddcml/bddcml_solver.i"
	@echo "... src/bddcml/bddcml_solver.s"
	@echo "... src/bddcml/bddcml_structs.o"
	@echo "... src/bddcml/bddcml_structs.i"
	@echo "... src/bddcml/bddcml_structs.s"
	@echo "... src/definitions.o"
	@echo "... src/definitions.i"
	@echo "... src/definitions.s"
	@echo "... src/element.o"
	@echo "... src/element.i"
	@echo "... src/element.s"
	@echo "... src/gauss_quadrature.o"
	@echo "... src/gauss_quadrature.i"
	@echo "... src/gauss_quadrature.s"
	@echo "... src/geometry_mesh.o"
	@echo "... src/geometry_mesh.i"
	@echo "... src/geometry_mesh.s"
	@echo "... src/integral.o"
	@echo "... src/integral.i"
	@echo "... src/integral.s"
	@echo "... src/integration_cell.o"
	@echo "... src/integration_cell.i"
	@echo "... src/integration_cell.s"
	@echo "... src/level_set.o"
	@echo "... src/level_set.i"
	@echo "... src/level_set.s"
	@echo "... src/local_matrix.o"
	@echo "... src/local_matrix.i"
	@echo "... src/local_matrix.s"
	@echo "... src/local_solution.o"
	@echo "... src/local_solution.i"
	@echo "... src/local_solution.s"
	@echo "... src/p4est/my_p4est_implementation.o"
	@echo "... src/p4est/my_p4est_implementation.i"
	@echo "... src/p4est/my_p4est_implementation.s"
	@echo "... src/p4est/my_p4est_interface.o"
	@echo "... src/p4est/my_p4est_interface.i"
	@echo "... src/p4est/my_p4est_interface.s"
	@echo "... src/p4est/my_p8est_implementation.o"
	@echo "... src/p4est/my_p8est_implementation.i"
	@echo "... src/p4est/my_p8est_implementation.s"
	@echo "... src/quadrature.o"
	@echo "... src/quadrature.i"
	@echo "... src/quadrature.s"
	@echo "... src/shapefun.o"
	@echo "... src/shapefun.i"
	@echo "... src/shapefun.s"
	@echo "... src/vtk_output.o"
	@echo "... src/vtk_output.i"
	@echo "... src/vtk_output.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

